name: Create Node Backend Repository

on:
  workflow_dispatch:
    inputs:
      repo_name:
        description: 'Name of the backend repository'
        required: true
        type: string
      description:
        description: 'Repository description'
        required: false
        default: 'A Node.js backend with Express'
      author_name:
        description: 'Author name'
        required: true
        type: string
      author_email:
        description: 'Author email'
        required: true
        type: string
      private:
        description: 'Private repository'
        required: false
        default: 'false'
        type: boolean

jobs:
  create-node-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Scaffold TypeScript Express backend
        run: |
          # create project directory and init
          mkdir "${{ github.event.inputs.repo_name }}"
          cd "${{ github.event.inputs.repo_name }}"
          npm init -y

          # install runtime & dev dependencies
          npm install express
          npm install --save-dev typescript ts-node-dev @types/node @types/express

          # write tsconfig.json
          cat << 'EOF' > tsconfig.json
          {
            "compilerOptions": {
              "target": "ES2020",
              "module": "CommonJS",
              "rootDir": "src",
              "outDir": "dist",
              "strict": true,
              "esModuleInterop": true,
              "skipLibCheck": true
            }
          }
          EOF

          # create src folder and empty entrypoint
          mkdir src
          touch src/index.ts

          # define npm scripts
          npm pkg set scripts.dev="ts-node-dev --respawn --transpile-only src/index.ts"
          npm pkg set scripts.build="tsc"
          npm pkg set scripts.start="node dist/index.js"


      - name: Create new GitHub repository
        run: |
          curl -X POST -H "Authorization: token ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}" \
            -d '{
                  "name": "${{ github.event.inputs.app_name }}",
                  "description": "${{ github.event.inputs.description }}",
                  "private": ${{ github.event.inputs.private }}
                }' \
            https://api.github.com/user/repos

      - name: Push to new repository
        run: |
          cd "${{ github.event.inputs.app_name }}"
          git config --global user.email "${{ github.event.inputs.author_email }}"
          git config --global user.name "${{ github.event.inputs.author_name }}"
          git init
          git add .
          git commit -m "Initialize React Native app with Expo"
          git branch -M main
          git remote add origin git@github.com:${{ github.actor }}/${{ github.event.inputs.app_name }}.git
          git remote set-url origin https://x-access-token:${{ env.GH_PERSONAL_ACCESS_TOKEN }}@github.com/${{ github.actor }}/${{ github.event.inputs.app_name }}
          git push -u origin main
        env:
          GH_PERSONAL_ACCESS_TOKEN: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
