name: Create React Native App Repository

on:
  workflow_dispatch:
    inputs:
      app_name:
        description: 'Name of the React Native app'
        required: true
        type: string
      description:
        description: 'Repository description'
        required: false
        default: 'A React Native app created with Expo'
      author_name:
        description: 'Author name'
        required: true
        type: string
      author_email:
        description: 'Author email'
        required: true
        type: string
      private:
        description: 'Private repository'
        required: false
        default: 'false'
        type: boolean

jobs:
  create-react-native-app:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          
      - name: Create React Native app
        run: npx create-expo-app ${{ github.event.inputs.app_name }}

      - name: Initialize git repository
        run: |
          cd ${{ github.event.inputs.app_name }}
          git init
          git add .
          git config --global user.email "${{ github.event.inputs.author_email }}"
          git config --global user.name "${{ github.event.inputs.author_name }}"
          git commit -m "Initial commit: Create React Native app with Expo"

      - name: Create new GitHub repository
        run: |
          curl -X POST -H "Authorization: token ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}" \
            -d '{
                  "name": "${{ github.event.inputs.app_name }}",
                  "description": "${{ github.event.inputs.description }}",
                  "private": ${{ github.event.inputs.private }}
                }' \
            https://api.github.com/user/repos

      - name: Push to new repository
        run: |
          cd "${{ github.event.inputs.app_name }}"
          git config --global user.email "${{ github.event.inputs.author_email }}"
          git config --global user.name "${{ github.event.inputs.author_name }}"
          git init
          git add .
          git commit -m "Initialize Electron project with ${{ github.event.inputs.build_tool }}"
          git branch -M main
          git remote add origin git@github.com:${{ github.actor }}/${{ github.event.inputs.repo_name }}.git
          git remote set-url origin https://x-access-token:${{ env.GH_PERSONAL_ACCESS_TOKEN }}@github.com/${{ github.actor }}/${{ github.event.inputs.repo_name }}
          git push -u origin main
        env:
          GH_PERSONAL_ACCESS_TOKEN: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
